---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: ghcr.io/dandyrow/podman-${MOLECULE_DISTRO:-archlinux}-ansible:latest
    pre_build_image: true
    command: ""
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
